import type { Lang } from "@/data/prompts";

export const UI: Record<Lang, Record<string, string>> = {
  en: {
    pageTitle: "Prompt Library",
    searchPlaceholder: "Search prompts...",
    unlockTitle: "Unlock the prompts",
    unlockBody:
      "Enter your email to access the copy-ready prompts from the ebook.",
    unlockButton: "Unlock",
    snapshotTitle: "Your Business Snapshot",
    snapshotDesc: "Fill in your details to personalize all prompts.",
    personalize: "Personalize prompts",
    copyPersonalized: "Copy personalized",
    copyTemplate: "Copy template",
    share: "Share",
    copied: "Copied!",
    linkCopied: "Link copied!",
    tipLabel: "Tip",
    fromPdf: "Welcome from the ebook!",
    industry: "Industry",
    offer: "Offer / Product",
    customers: "Target customers",
    goal: "Main goal",
    bottleneck: "Biggest bottleneck",
    product: "Product",
    audience: "Target audience",
    platform: "Platform",
    niche: "Niche",
    tone: "Tone",
    task: "Task to automate",
    tools: "Tools you use",
    frequency: "How often",
  },
  es: {
    pageTitle: "Biblioteca de Prompts",
    searchPlaceholder: "Buscar prompts...",
    unlockTitle: "Desbloquear prompts",
    unlockBody:
      "Ingresa tu email para acceder a los prompts listos para copiar.",
    unlockButton: "Desbloquear",
    snapshotTitle: "Resumen de tu Negocio",
    snapshotDesc: "Completa tus datos para personalizar todos los prompts.",
    personalize: "Personalizar prompts",
    copyPersonalized: "Copiar personalizado",
    copyTemplate: "Copiar plantilla",
    share: "Compartir",
    copied: "\u00a1Copiado!",
    linkCopied: "\u00a1Link copiado!",
    tipLabel: "Tip",
    fromPdf: "\u00a1Bienvenido desde el ebook!",
    industry: "Industria",
    offer: "Oferta / Producto",
    customers: "Clientes objetivo",
    goal: "Objetivo principal",
    bottleneck: "Mayor cuello de botella",
    product: "Producto",
    audience: "Audiencia objetivo",
    platform: "Plataforma",
    niche: "Nicho",
    tone: "Tono",
    task: "Tarea a automatizar",
    tools: "Herramientas que usas",
    frequency: "Con qu\u00e9 frecuencia",
  },
};
