export const COPY: Record<string, Record<string, string>> = {
  en: {
    bRole: "AI \u2022 Marketing \u2022 Business",
    nStart: "Start",
    nContent: "Content",
    nEbooks: "eBooks",
    nWork: "Work with me",
    nNews: "Newsletter",
    kicker: "Visual-first playbooks (no long reading)",
    title: "AI + marketing that turns into leads, sales and systems.",
    subtitle: "Short videos. Clean visuals. Simple steps you can copy today.",
    cta1: "Get free resources",
    cta2: "Book mentoring",
    cta3: "Join community",
    chip1: "Mobile-first",
    chip2: "Fast loading",
    chip3: "ES/EN content",
    chip4: "AI \u2022 Business \u2022 Marketing",
    t1: "AI",
    t1s: "Tools, prompts, agents and workflows that actually help.",
    t2: "Marketing",
    t2s: "Hooks, ads, content systems, and conversion basics.",
    t3: "Business",
    t3s: "Offer, pricing, funnels, and simple execution plans.",
    socialTitle: "Follow me",
    eTitle: "Free eBooks (EN + ES)",
    eSub: "Short, visual guides. Download in your language.",
    e1tag: "AI START",
    e1: "AI for Business \u2014 7 days",
    e1s: "Prompts + tools + quick wins.",
    e2tag: "MARKETING",
    e2: "Marketing that converts",
    e2s: "Hooks, offers, and simple funnels.",
    e3tag: "AUTOMATION",
    e3: "Automate your workflow",
    e3s: "No-code automations that save hours.",
    e4tag: "SALES",
    e4: "Sales & Offers Starter",
    e4s: "Offers, pricing, objections, and closing.",
    eBtn: "Download",
    dlGateTitle: "Get your free ebook",
    dlGateBody: "Enter your name and email to download.",
    dlGateName: "First name",
    dlGateEmail: "Email",
    dlGateBtn: "Download now",
    dlGateNameErr: "Name must be at least 2 characters.",
    dlGateEmailErr: "Enter a valid email address.",
    dlGateServerErr: "Something went wrong. Try again.",
    wTitle: "Work with me",
    wSub: "Mentoring \u2022 audits \u2022 build-with-you systems.",
    w1: "Book a call",
    w2: "Send a message",
    nTitle: "Newsletter (choose your topic)",
    nSub: "You select what you want: Marketing, Business, AI, or All-in-one.",
    emailPh: "Email",
    subBtn: "Subscribe",
    ckMt: "Marketing",
    ckMs: "Ads, hooks, content systems, conversion.",
    ckBt: "Business",
    ckBs: "Offers, pricing, growth, operations.",
    ckAt: "AI",
    ckAs: "Tools, prompts, automations, agents.",
    ckAllt: "All-in-one",
    ckAlls: "A curated mix of the best insights.",
    footHint: "Video-first + fast visuals + ES/EN smart links",
    subSuccess: "You're in! Check your inbox.",
    subError: "Something went wrong. Try again.",
  },
  es: {
    bRole: "IA \u2022 Marketing \u2022 Negocios",
    nStart: "Inicio",
    nContent: "Contenido",
    nEbooks: "eBooks",
    nWork: "Trabaja conmigo",
    nNews: "Newsletter",
    kicker: "Gu\u00edas visuales (sin leer tanto)",
    title: "IA + marketing que se convierte en leads, ventas y sistemas.",
    subtitle: "Videos cortos. Visual limpio. Pasos simples que puedes copiar hoy.",
    cta1: "Recursos gratis",
    cta2: "Agendar mentor\u00eda",
    cta3: "Unirme a la comunidad",
    chip1: "Mobile-first",
    chip2: "Carga r\u00e1pida",
    chip3: "Contenido ES/EN",
    chip4: "IA \u2022 Negocios \u2022 Marketing",
    t1: "IA",
    t1s: "Herramientas, prompts, agentes y flujos que s\u00ed ayudan.",
    t2: "Marketing",
    t2s: "Hooks, anuncios, sistema de contenido y conversi\u00f3n.",
    t3: "Negocios",
    t3s: "Oferta, precio, embudo y plan de ejecuci\u00f3n.",
    socialTitle: "S\u00edgueme",
    eTitle: "eBooks Gratis (ES + EN)",
    eSub: "Gu\u00edas cortas y visuales. Descarga en tu idioma.",
    e1tag: "IA INICIO",
    e1: "IA para negocios \u2014 7 d\u00edas",
    e1s: "Prompts + herramientas + resultados r\u00e1pidos.",
    e2tag: "MARKETING",
    e2: "Marketing que convierte",
    e2s: "Hooks, oferta y embudos simples.",
    e3tag: "AUTOMATIZACI\u00d3N",
    e3: "Automatiza tu trabajo",
    e3s: "Automatizaciones no-code que ahorran horas.",
    e4tag: "VENTAS",
    e4: "Ventas y Ofertas Starter",
    e4s: "Ofertas, precios, objeciones y cierre.",
    eBtn: "Descargar",
    dlGateTitle: "Obt\u00e9n tu ebook gratis",
    dlGateBody: "Ingresa tu nombre y correo para descargar.",
    dlGateName: "Nombre",
    dlGateEmail: "Correo",
    dlGateBtn: "Descargar ahora",
    dlGateNameErr: "El nombre debe tener al menos 2 caracteres.",
    dlGateEmailErr: "Ingresa un correo v\u00e1lido.",
    dlGateServerErr: "Algo sali\u00f3 mal. Intenta de nuevo.",
    wTitle: "Trabaja conmigo",
    wSub: "Mentor\u00edas \u2022 auditor\u00edas \u2022 sistemas contigo.",
    w1: "Agendar",
    w2: "Enviar mensaje",
    nTitle: "Newsletter (elige tu tema)",
    nSub: "T\u00fa eliges: Marketing, Negocios, IA o Todo-en-uno.",
    emailPh: "Correo",
    subBtn: "Suscribirme",
    ckMt: "Marketing",
    ckMs: "Ads, hooks, contenido, conversi\u00f3n.",
    ckBt: "Negocios",
    ckBs: "Oferta, precios, crecimiento, operaciones.",
    ckAt: "IA",
    ckAs: "Herramientas, prompts, automatizaci\u00f3n, agentes.",
    ckAllt: "Todo-en-uno",
    ckAlls: "Selecci\u00f3n curada de lo mejor.",
    footHint: "Video primero + visual r\u00e1pido + links inteligentes ES/EN",
    subSuccess: "\u00a1Listo! Revisa tu bandeja.",
    subError: "Algo sali\u00f3 mal. Intenta de nuevo.",
  },
};
